# Use postgres/example user/password credentials
version: '3.1'

services:
  postgres:
    container_name: pets_pg
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - petspgdata:/var/lib/petspg/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=admin

volumes:
  petspgdata:
