# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@3.1.0
  awsebcli: sbc-orbs/awsebcli@0.0.3
#notify:
#  webhooks:
#  - url: https://pru.appsimples.com.br/hooks/RXe5MFvQGspYYcxAj/CqR93J4SoCAv4ypHhyzt6AAnTCBv98eW7LT9Qwhg7E3hnDh7
jobs:
#  release-development:
#    docker:
#    - image: circleci/node:7.10
#    working_directory: ~/repo
#    steps:
#    - checkout
#    - restore_cache:
#        name: Restore Yarn Package Cache
#        key: yarn-packages-{{ checksum "yarn.lock" }}
#    - run:
#        name: Installing Dependencies
#        command: yarn install --frozen-lockfile
#    - save_cache:
#        name: Save Yarn Package Cache
#        key: yarn-packages-{{ checksum "yarn.lock" }}
#        paths:
#        - ~/.cache/yarn
#    - run:
#        name: Deploy development
#        command: yarn deploy:development


  release-development:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_REPO_URL
          repo: ${AWS_RESOURCE_NAME_PREFIX}
          region: AWS_DEFAULT_REGION
          tag: latest
          checkout: false
          extra-build-args: -e NODE_ENV='staging'
      - run:
          name: Install Elastic Beanstalk cli
          command: |
            sudo pip install awsebcli --upgrade
      - run:
          name: Deploy to Elastic Beanstalk
          command: |
            eb deploy NodeTypeorm-env

  release-production:
    docker:
    - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache: # special step to restore the dependency cache
        name: Restore Yarn Package Cache
        key: yarn-packages-{{ checksum "yarn.lock" }}
    - run:
        name: Installing Dependencies
        command: yarn install
    - save_cache:
        name: Save Yarn Package Cache
        key: yarn-packages-{{ checksum "yarn.lock" }}
        paths:
        - ~/.cache/yarn
    - run:
        name: Deploy Production
        command: yarn deploy:production

workflows:
  version: 2.1
  deploy-development:
    jobs:
#    - aws-ecr/build_and_push_image:
#        account-url: AWS_ECR_REPO_URL
#        repo: ${AWS_RESOURCE_NAME_PREFIX}
#        region: AWS_DEFAULT_REGION
#        tag: latest
    - release-development:
#        requires:
#          - aws-ecr/build_and_push_image
        filters:
          branches:
            only:
            - feat/ciTest

  build-and-deploy-staging:
    jobs:
    - release-development:
        filters:
          branches:
            only:
            - /^release.*/
